
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: oauth2-fullstack
  labels:
    app: fastapi
spec:
  replicas: 1
  strategy:
      type: RollingUpdate
  selector:
    matchLabels:
      app: fastapi
      tier: backend
  template:
    metadata:
      labels:
        app: fastapi
        tier: backend
    spec:
      containers:
        - name: fastapi-container
          envFrom:
            - secretRef:
                name: fastapi
          image: jasonbigcow/oauth2-fastapi:linux
          # imagePullPolicy: Always
          imagePullPolicy: Never
          ports:
            - containerPort: 5001