
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: oauth2-fullstack
spec:
  replicas: 1
  strategy:
      type: RollingUpdate
  selector:
    matchLabels:
      app: fastapi
      tier: backend
  template:
    metadata:
      labels:
        app: fastapi
        tier: backend
    spec:
      containers:
        - name: fastapi
          envFrom:
            - secretRef:
                name: fastapi
          image: jasonbigcow/oauth2-fastapi:linux
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "100m"