apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: oauth2-fullstack
  labels:
    app: my-app
spec:
  containers:
    - name: backend-test
      image: jasonbigcow/oauth2-fastapi:linux
      ports:
        - containerPort: 5001
      envFrom:
        - secretRef:
            name: fastapi
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
        requests:
          cpu: "0.5"
          memory: "256Mi"
