apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: oauth2-fullstack
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5001
  selector:
    app: fastapi
    tier: backend
