---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: oauth2-fullstack
spec:
  progressDeadlineSeconds: 600
  minReadySeconds: 0
  selector:
    matchLabels:
      app: nginx-vue3
      tier: frontend
  replicas: 1
  strategy:
      type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-vue3
        tier: frontend
    spec:
      containers:
        - name: nginx-vue3
          image: jasonbigcow/oauth2-vue3-nginx:linux
          # imagePullPolicy: Always
          imagePullPolicy: Never